name = "Algolean"
version = "0.1.0"
keywords = ["computer science", "algorithms"]
defaultTargets = ["Algolean"]
testDriver = "AlgoleanTests"
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "Cslib"
scope = "leanprover"
rev = "v4.29.0"

[[require]]
name = "Physlib"
git = "https://github.com/leanprover-community/physlib.git"
rev = "v4.29.0"

[[lean_lib]]
name = "Algolean"

[[lean_lib]]
name = "AlgoleanTests"
globs = ["AlgoleanTests.+"]
