name: Lean Action CI

on:
  push:
    branches:
      - main
      - test-CI
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set TEST_ARGS manually
        run: |
          echo "TEST_ARGS='--wfail --iofail'" >> $GITHUB_ENV
        shell: bash
      - uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail --iofail"
          test-args: "--wfail --iofail"
      - name: "lake exe mk_all --check --module"
        run: |
          set -e
          lake exe mk_all --check --module

  
